# Generated by Django 2.2.19 on 2021-02-20 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=50)),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CandidateFinder.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=50)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CandidateFinder.Job')),
                ('skill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CandidateFinder.Skill')),
            ],
        ),
    ]
