# Generated by Django 2.2.19 on 2021-02-21 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CandidateFinder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='skill_id',
        ),
        migrations.RemoveField(
            model_name='job',
            name='skill_id',
        ),
        migrations.AddField(
            model_name='candidate',
            name='job_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='CandidateFinder.Skill'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='skill_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='CandidateFinder.Skill'),
        ),
        migrations.AddField(
            model_name='skill',
            name='job_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CandidateFinder.Job'),
        ),
    ]
