# Generated by Django 2.2.19 on 2021-02-21 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CandidateFinder', '0002_auto_20210221_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='job_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job', to='CandidateFinder.Job'),
        ),
    ]
