# Generated by Django 2.2.19 on 2021-02-21 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CandidateFinder', '0003_auto_20210221_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='candidate_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='skill_name',
            new_name='skill',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='job_name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='job_name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='skill_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='job_name',
        ),
        migrations.AddField(
            model_name='job',
            name='skill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CandidateFinder.Skill'),
        ),
    ]
