# Generated by Django 2.2.19 on 2021-02-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CandidateFinder', '0004_auto_20210221_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='title',
            new_name='job_title',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='name',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
