# Generated by Django 2.2.19 on 2021-02-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CandidateFinder', '0005_auto_20210221_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_title',
            field=models.CharField(choices=[('Software Developer', 'Software Developer'), ('Back-end Developer', 'Back-end Developer'), ('Front-end Developer', 'Front-end Developer')], default='Software Developer', max_length=50),
        ),
    ]
