# Generated by Django 2.2.19 on 2021-02-21 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CandidateFinder', '0008_auto_20210221_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CandidateFinder.Job'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(choices=[('Java', 'Java'), ('C', 'C'), ('C++', 'C++'), ('SQL', 'SQL'), ('NodeJS', 'NodeJS'), ('django', 'django'), ('VueJS', 'VueJS'), ('React', 'React')], max_length=50, null=True),
        ),
    ]
