# Generated by Django 2.2.19 on 2021-02-21 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CandidateFinder', '0009_auto_20210222_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
